# Generated by Django 5.0.1 on 2024-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin Descripción', max_length=250),
        ),
    ]
