# Generated by Django 6.0.3 on 2026-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin Descripción', max_length=450),
        ),
    ]
